# Generated by Django 5.0.7 on 2024-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='clicon',
            field=models.CharField(db_column='CliCon', max_length=500),
        ),
    ]
