# Generated by Django 5.0.7 on 2024-07-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='percon',
            field=models.CharField(db_column='PerCon', max_length=500),
        ),
    ]
