# Generated by Django 5.0.7 on 2024-07-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='serima',
            field=models.CharField(db_column='SerIma', default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='serdes',
            field=models.CharField(blank=True, db_column='SerDes', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='serdur',
            field=models.CharField(blank=True, db_column='SerDur', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='sernom',
            field=models.CharField(db_column='SerNom', max_length=100, unique=True),
        ),
    ]
