# Generated by Django 5.0.7 on 2024-07-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_estadopersonal_estpercod_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoPersonal',
        ),
    ]
