# Generated by Django 5.0.7 on 2024-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_delete_estadopersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoregistro',
            name='estregcod',
            field=models.CharField(db_column='EstRegCod', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estadoregistro',
            name='estregnom',
            field=models.CharField(db_column='EstRegNom', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipopersonal',
            name='tippercod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopersonal',
            name='tippernom',
            field=models.CharField(max_length=100),
        ),
    ]
