# Generated by Django 5.0.7 on 2024-07-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_estadoregistro_estregcod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoregistro',
            name='estregcod',
            field=models.CharField(db_column='EstRegCod', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopersonal',
            name='tippercod',
            field=models.CharField(db_column='TipPerCod', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopersonal',
            name='tippernom',
            field=models.CharField(db_column='TipPerNom', max_length=100),
        ),
    ]
