# Generated by Django 5.0.7 on 2024-07-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_cliente_clicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proimg',
            field=models.ImageField(blank=True, db_column='ProImaPmg', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='EventoProducto',
            fields=[
                ('evecod', models.AutoField(primary_key=True, serialize=False)),
                ('evedes', models.CharField(blank=True, max_length=150, null=True)),
                ('evefec', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='CliDni', null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
                ('procod', models.ForeignKey(db_column='ProCod', on_delete=django.db.models.deletion.PROTECT, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Evento de Producto',
                'verbose_name_plural': 'Eventos de Productos',
                'db_table': 'evento_producto',
            },
        ),
    ]
